// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryqpblgvzekqzkpbabyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5cXBibGd2emVrcXprcGJhYnlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTczNzEsImV4cCI6MjA2MjM5MzM3MX0.8w9T1lg_-d_noZ8unInh-V6e5WSLdskhBqxrSnilLE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);